# use for application.properties
# spring.jpa.hibernate.ddl-auto=update
# spring.datasource.url=jdbc:mysql://localhost:3306/usercomment
# spring.datasource.username=bkpflo
# spring.datasource.password=1
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# server.error.include-message=always
# spring.jpa.show-sql: true

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1
    url: jdbc:mysql://localhost:3306/usercomment
    username: bkpflo
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true

    # driverClassName: com.mysql.jdbc.Driver
